#cc_library(
#  name = "static_vector",
#  srcs = ["static_vector.cc"],
#  hdrs = ["static_vector.h"],
#)

cc_binary(
  name = "vector",
  srcs = ["vector.cc"],
  deps = [
      "//lib:static_vector",
      ],
)
